const quotes = [
  "Politicians should vote according to their beliefs, without worrying about whether their constituents agree with those beliefs.",
  "Creative inspiration, rather than careful planning, often results in the best solution to a problem.",
  "Concerned individuals are often better than the government at solving society's problems.",
  "The object of education should be to teach skills, not values.",
  "There are as many versions of history as there are historians.",
  "An orderly society must never compromise in matters of law.",
  "A law must be enforced to be effective.",
  "In advertising, truth is irrelevant.",
  "Progress seldom comes from the deliberations of a group. Rather, progress most often comes from the creative thinking of individuals working alone.",
  "No matter how oppressive a government, violent revolution is never justified.",
  "Students should be more interested in the process of learning than in the facts learned.",
  "A country must use its natural resources in a way agreeable to all its citizens.",
  "In education, the newest way is not always the best way.",
  "Although it claims to promote individuality, most advertising promotes conformity.",
  "A democratic government is never justified in keeping secrets from the voting public.",
  "In business, quick solutions often do not address the real source of a problem.",
  "In business, competition is superior to cooperation.",
  "Scientific inquiry is rooted in the desire to discover, but there is not discovery so important that in its pursuit a threat to human life can be tolerated.",
  "It is each citizen's duty to obey the laws of the nation.",
  "In the recording of history, it is impossible to be objective.",
  "Violence is sometimes necessary to achieve social change.",
  "Environmental concerns should always take priority over economic concerns.",
  "The more people rely on computers, the more people become alienated from one another.",
  "Drastic action is sometimes the only way to bring about political change.",
  "Society is best served by giving people as much freedom as possible.",
  "A nation's ability to survive is often dependent upon its military strength.",
  "Education comes not from books but from practical experience.",
  "In a free society, laws must be subject to change.",
  "An understanding of the past is necessary for solving the problems of the present.",
  "Politicians too often base their decisions on what will please the voters, not on what is best for the country.",
  "Technology designed to make our lives simpler often turns out instead to make our lives more complicated.",
  "Music has the power to entertain, but seldom to educate.",
  "Once a democracy elects its leaders, citizens should be able to trust those leaders to decide what is best for the country.",
  "In business, using a successful method for too long may lead to failure.",
  "Revolutions often destroy more than they create.",
  "The benefits of a competitive society extend only to those willing to compete.",
  "In business, the notion of progress is often just an excuse for making more money.",
  "Those who own land have the right to do with it as they choose.",
  "The public's right to know must sometimes take precedence over an individual's right to privacy.",
  "Nonconformity is sometimes necessary in order for society to progress.",
  "When there is a choice between obeying the law and following one's own beliefs, it is best to follow one's beliefs.",
  "The function of the press should be to report only the facts of daily events, not to influence the public's opinion about those facts.",
  "A country's strength increases in direct proportion to its freedoms.",
  "The media's use of unethical investigative practices is never justified.",
  "Our belief in an idea only lasts until the introduction of the next idea.",
  "In politics, the most popular course of action is usually the correct course of action.",
  "Successful leadership is a matter of allowing everyone to share responsibility.",
  "In politics, campaign promises are seldom kept after the election is won.",
  "It is sometimes necessary to restrict individual freedom for the sake of social order.",
  "New developments in technology have caused us to become less creative.",
  "Citizens who enjoy a country's benefits during peacetime have a responsibility to support their nation in time of war.",
  "The best politician is the one most removed from politics.",
  "The public's right to information should override the government's need for security.",
  "Formal schooling often provides to be the most important part of learning.",
  "Governments have a responsibility to regulate companies that provide necessary services to citizens.",
  "Only those politicians who have learned the art of compromise can achieve their political goals.",
  "Government policy should be directed at addressing the needs of the presents.",
  "Truth is an ideal to which all researchers should aspire, but they should never assume they have actually found it.",
  "In politics, money equals power.",
  "A government must sometimes require its citizens to do things they may not want to do.",
  "Most advertising is designed to prevent consumers from making rational choices.",
  "The essential function of law in a democracy is to protect individual rights.",
  "In a truly free and open society, censorship of the press can never be justified.",
  "In business, success is often due to the mistakes of others.",
  "The role of technology should be to improve human life, but not to affect human values.",
  "A business's main purpose should be to make profit.",
  "Youth and innovation are sometimes more beneficial in politics than are age and experience.",
  "Caution is often the best guide for government.",
  "A person who enters public life is necessarily forced to surrender some degree of personal privacy.",
  "Wealthy politicians cannot offer fair representation to all the people.",
  "The more people rely on computers, the more people become alienated from one another.",
  "Progress often complicates as much as it simplifies.",
  "Laws cannot change social values."
];

export default quotes;
